import Head from 'next/head';

import styled from 'styled-components';
import Link from 'next/link';

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;
  height: 100vh;
`;

const Text = styled.p`
  font-size: 34px;
  color: #ff9d00;

  text-align: center;
`;

const StLink = styled(Link)`
  font-size: 46px;
  color: #ff9d00;

  padding: 6px 12px 6px 12px;

  border: 1px solid #ff9d00;
  border-radius: 8px;

  text-decoration: none;

  transition: transform 0.3s ease, background-color 0.3s ease;

  &:hover {
    transform: scale(1.1); 
    background-color: #a5660055; 
  }
`;

const Home = () => {
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Wrapper>
        <Text>Использовать TaskManager</Text>
        <StLink href="/all">Начать</StLink>
      </Wrapper>
    </>
  );
};

export default Home;
