import { useContext } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styled from 'styled-components';

import { RegistationButton } from '../src/components/buttons/registration';
import { LoginButton } from '../src/components/buttons/login';

import { ModalsContext } from './_app';

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;

  height: 100vh;
`;

const Text = styled.p`
  font-size: 34px;
  color: #ff9d00;

  text-align: center;
`;

const StLink = styled(Link)`
  font-size: 46px;
  color: #ff9d00;

  padding: 6px 12px 6px 12px;

  border: 1px solid #ff9d00;
  border-radius: 8px;

  text-decoration: none;

  transition: transform 0.3s ease, background-color 0.3s ease;

  &:hover {
    transform: scale(1.1);
    background-color: #a5660055;
  }
`;

const Home = () => {
  const { openModal } = useContext(ModalsContext);

  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Wrapper>
        <Text>Использовать TaskManager</Text>
        <StLink href="/all">Начать</StLink>
        <LoginButton onClick={() => openModal('login')} />
        <RegistationButton onClick={() => openModal('registration')} />
      </Wrapper>
    </>
  );
};

export default Home;
